In [1]:
# Import dependencies
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

In [5]:
# load the iris data
iris = datasets.load_iris()
iris.data.shape,iris.target.shape # .target attribute stroes the class of each observation


((150, 4), (150,))

In [12]:
# Sample a training set, 60/40%
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.4, random_state=0)
# check the shape of the train/test sets
X_train.shape, y_train.shape
X_test.shape, y_test.shape
# create a classifier model using SVM linear kernal, run on test set
# C is penalty hyperparameter
clf=svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
# fit the svm model according to the given trianin data
clf.fit(X_test, y_test)
# returns the mean accuracy on the given test data
clf.score(X_test, y_test)
# Perfoms classification on samples in X
clf. predict(X_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0,
       0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0, 0, 1,
       2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2])

In [14]:
# Compute cross validated metrics
from sklearn.model_selection import cross_val_score
clf=svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf, iris.data, iris.target, cv=5)
scores

array([ 0.96666667,  1.        ,  0.96666667,  0.96666667,  1.        ])

In [15]:
# Resulting mean score and 95% conf interval of the scores
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() *2))

Accuracy: 0.98 (+/- 0.03)


In [18]:
# change the scoring parameter
from sklearn import metrics
scores= cross_val_score(clf, iris.data, iris.target, cv=5, scoring='f1_macro')
scores

array([ 0.96658312,  1.        ,  0.96658312,  0.96658312,  1.        ])

In [20]:
# use a cross validation iterator
from sklearn.model_selection import ShuffleSplit
n_samples=iris.data.shape[0]
cv=ShuffleSplit(n_splits=3, test_size=0.3, random_state=0)
cross_val_score(clf, iris.data, iris.target, cv=cv)

array([ 0.97777778,  0.97777778,  1.        ])

In [21]:
# Data transformation with held out data
from sklearn import preprocessing
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.4, random_state=0)
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_transformed = scaler.transform(X_train)
clf = svm.SVC(C=1).fit(X_train_transformed, y_train)
X_test_transformed = scaler.transform(X_test)
clf.score(X_test_transformed, y_test) 

0.93333333333333335

In [24]:
# a Pipeline makes it easiser to compose estimators, providing this behavior under
# cross validation
from sklearn.pipeline import make_pipeline
clf = make_pipeline(preprocessing.StandardScaler(),svm.SVC(C=1))
cross_val_score(clf, iris.data, iris.target, cv=cv)

array([ 0.97777778,  0.93333333,  0.95555556])

In [25]:
# obtaining predictions by CV
from sklearn.model_selection import cross_val_predict
predicted=cross_val_predict(clf, iris.data, iris.target, cv=10)
metrics.accuracy_score(iris.target, predicted)

0.96666666666666667